"""
streamlit_app.py
-------------------
Interactive GUI for the Data Classification Using AI project.

Run with (from the project root, after main.py has been run once):
    streamlit run app/streamlit_app.py

Features
--------
- Manual input of the 13 chemical features via sliders (with sensible
  default/realistic ranges) to get a live prediction + confidence.
- Batch prediction via CSV upload.
- A "Model Performance" tab showing the comparison chart, confusion
  matrices and ROC curves generated by src/evaluate.py.
- A "Dataset Overview" tab with EDA-style visuals.
"""

from pathlib import Path
import json
import sys

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.append(str(PROJECT_ROOT / "src"))

MODELS_DIR = PROJECT_ROOT / "models"
DATA_DIR = PROJECT_ROOT / "data"
FIGURES_DIR = PROJECT_ROOT / "reports" / "figures"

CLASS_LABELS = {0: "Cultivar A (class_0)", 1: "Cultivar B (class_1)", 2: "Cultivar C (class_2)"}

FEATURE_RANGES = {
    "alcohol": (11.0, 15.0, 13.0, 0.1),
    "malic_acid": (0.7, 5.8, 2.3, 0.1),
    "ash": (1.3, 3.3, 2.4, 0.05),
    "alcalinity_of_ash": (10.6, 30.0, 19.5, 0.5),
    "magnesium": (70.0, 162.0, 99.7, 1.0),
    "total_phenols": (0.9, 3.9, 2.3, 0.05),
    "flavanoids": (0.3, 5.1, 2.0, 0.05),
    "nonflavanoid_phenols": (0.1, 0.7, 0.36, 0.01),
    "proanthocyanins": (0.4, 3.6, 1.6, 0.05),
    "color_intensity": (1.3, 13.0, 5.1, 0.1),
    "hue": (0.4, 1.8, 0.96, 0.02),
    "od280/od315_of_diluted_wines": (1.3, 4.0, 2.6, 0.05),
    "proline": (278.0, 1680.0, 746.0, 5.0),
}


@st.cache_resource
def load_artifacts():
    scaler = joblib.load(MODELS_DIR / "scaler.pkl")
    feature_cols = joblib.load(MODELS_DIR / "feature_columns.pkl")
    with open(MODELS_DIR / "training_summary.json") as f:
        summary = json.load(f)
    models = {name: joblib.load(MODELS_DIR / info["file"]) for name, info in summary.items()}
    with open(MODELS_DIR / "best_model_name.json") as f:
        best_name = json.load(f)["best_model"]
    return scaler, feature_cols, models, summary, best_name


def predict_single(model, scaler, feature_cols, input_dict):
    X = pd.DataFrame([input_dict])[feature_cols]
    X_scaled = pd.DataFrame(scaler.transform(X), columns=feature_cols)
    pred = model.predict(X_scaled)[0]
    proba = model.predict_proba(X_scaled)[0] if hasattr(model, "predict_proba") else None
    return pred, proba


def main():
    st.set_page_config(
        page_title="Data Classification Using AI",
        page_icon="🍷",
        layout="wide",
    )

    st.title("🍷 Data Classification Using AI")
    st.caption(
        "Multi-model machine learning pipeline for classifying wine cultivars from "
        "13 chemical properties — Internship Project, AI Track"
    )

    if not (MODELS_DIR / "training_summary.json").exists():
        st.error(
            "No trained models found. Please run `python main.py` from the project "
            "root first to train the models, then reload this app."
        )
        st.stop()

    scaler, feature_cols, models, summary, best_name = load_artifacts()

    tab1, tab2, tab3, tab4 = st.tabs(
        ["🔮 Live Prediction", "📁 Batch Prediction (CSV)", "📊 Model Performance", "📈 Dataset Overview"]
    )

    # ---------------- TAB 1 : Live single prediction ----------------
    with tab1:
        st.subheader("Predict a Wine's Cultivar from its Chemical Profile")

        col_left, col_right = st.columns([1, 1])
        with col_left:
            model_choice = st.selectbox(
                "Choose a trained model",
                options=list(models.keys()),
                index=list(models.keys()).index(best_name),
                help="'%s' achieved the best test-set accuracy during evaluation." % best_name,
            )
        with col_right:
            st.metric("Cross-validated accuracy of selected model",
                       f"{summary[model_choice]['best_cv_accuracy']*100:.2f}%")

        st.markdown("#### Enter chemical measurements")
        input_dict = {}
        cols = st.columns(3)
        for i, (feat, (lo, hi, default, step)) in enumerate(FEATURE_RANGES.items()):
            with cols[i % 3]:
                input_dict[feat] = st.slider(feat.replace("_", " ").title(), lo, hi, default, step)

        if st.button("🔍 Classify Wine", type="primary", use_container_width=True):
            model = models[model_choice]
            pred, proba = predict_single(model, scaler, feature_cols, input_dict)

            st.success(f"### Predicted class: **{CLASS_LABELS[pred]}**")

            if proba is not None:
                proba_df = pd.DataFrame({
                    "Class": [CLASS_LABELS[i] for i in range(len(proba))],
                    "Probability": proba,
                }).sort_values("Probability", ascending=False)
                st.bar_chart(proba_df.set_index("Class"))
                st.dataframe(proba_df.style.format({"Probability": "{:.2%}"}), use_container_width=True)

    # ---------------- TAB 2 : Batch prediction ----------------
    with tab2:
        st.subheader("Upload a CSV for Batch Classification")
        st.caption(f"CSV must contain these {len(feature_cols)} columns: " + ", ".join(feature_cols))

        model_choice_batch = st.selectbox(
            "Model to use for batch prediction", options=list(models.keys()),
            index=list(models.keys()).index(best_name), key="batch_model",
        )
        uploaded = st.file_uploader("Upload CSV file", type=["csv"])

        if uploaded is not None:
            batch_df = pd.read_csv(uploaded)
            missing_cols = set(feature_cols) - set(batch_df.columns)
            if missing_cols:
                st.error(f"Uploaded file is missing required columns: {missing_cols}")
            else:
                model = models[model_choice_batch]
                X_scaled = pd.DataFrame(
                    scaler.transform(batch_df[feature_cols]), columns=feature_cols
                )
                preds = model.predict(X_scaled)
                batch_df["predicted_class"] = [CLASS_LABELS[p] for p in preds]
                st.success(f"Classified {len(batch_df)} rows.")
                st.dataframe(batch_df, use_container_width=True)
                st.download_button(
                    "⬇ Download predictions as CSV",
                    batch_df.to_csv(index=False).encode("utf-8"),
                    file_name="wine_predictions.csv",
                    mime="text/csv",
                )

    # ---------------- TAB 3 : Model performance ----------------
    with tab3:
        st.subheader("Model Comparison — Test Set")
        cmp_path = FIGURES_DIR / "model_comparison.png"
        if cmp_path.exists():
            st.image(str(cmp_path), use_container_width=True)

        st.markdown("#### Cross-Validated Accuracy per Model")
        summary_df = pd.DataFrame(summary).T[["best_cv_accuracy", "train_time_sec"]]
        summary_df.columns = ["CV Accuracy", "Training Time (s)"]
        st.dataframe(
            summary_df.sort_values("CV Accuracy", ascending=False).style.format(
                {"CV Accuracy": "{:.2%}", "Training Time (s)": "{:.2f}"}
            ),
            use_container_width=True,
        )

        st.markdown("#### Detailed Diagnostics per Model")
        chosen = st.selectbox("Select a model to inspect", options=list(models.keys()), key="diag_model")
        safe_name = chosen.lower().replace(" ", "_").replace("(", "").replace(")", "")
        col1, col2 = st.columns(2)
        with col1:
            cm_path = FIGURES_DIR / f"cm_{safe_name}.png"
            if cm_path.exists():
                st.image(str(cm_path), caption="Confusion Matrix", use_container_width=True)
        with col2:
            roc_path = FIGURES_DIR / f"roc_{safe_name}.png"
            if roc_path.exists():
                st.image(str(roc_path), caption="ROC Curves (One-vs-Rest)", use_container_width=True)

        fi_path = FIGURES_DIR / "feature_importance_best_model.png"
        if fi_path.exists():
            st.markdown(f"#### Feature Importance — Best Model ({best_name})")
            st.image(str(fi_path), use_container_width=True)

    # ---------------- TAB 4 : Dataset overview ----------------
    with tab4:
        st.subheader("Dataset Overview")
        raw_path = DATA_DIR / "raw" / "wine_dataset.csv"
        if raw_path.exists():
            raw_df = pd.read_csv(raw_path)
            c1, c2, c3 = st.columns(3)
            c1.metric("Total samples", len(raw_df))
            c2.metric("Features", len(feature_cols))
            c3.metric("Classes", raw_df["target"].nunique())

            st.markdown("#### Class Distribution")
            st.bar_chart(raw_df["target_name"].value_counts())

            st.markdown("#### Sample Data")
            st.dataframe(raw_df.head(10), use_container_width=True)

            st.markdown("#### Feature Correlation Heatmap")
            fig, ax = plt.subplots(figsize=(10, 8))
            corr = raw_df[feature_cols].corr()
            sns.heatmap(corr, cmap="coolwarm", center=0, annot=False, ax=ax)
            st.pyplot(fig)

    st.divider()
    st.caption(
        "Internship Project — Data Classification Using AI | Built with scikit-learn & Streamlit"
    )


if __name__ == "__main__":
    main()
